
stream-generator:
  hosts:
    alfa:
      host: localhost
      port: 2222
    beta:
      host: localhost
      port: 3333
    gamma:
      host: localhost
      port: 4444

  max-items:  500

server:
  port: 9191